server:
  port: 8080


spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/koisystem"
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

  main:
    allow-circular-references: true