server:
  port: 8081


spring:
  datasource:
    url: "jdbc:mysql://103.90.227.68/koisystem"
    username: root
    password: swp@123


  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true


  main:
    allow-circular-references: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: haonc.t2.1922@gmail.com
    password: ajhq vsmu gxdk waol
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    default-encoding: UTF-8

    thymeleaf:
      prefix: classpath:/templates/
      suffix: .html
      mode: HTML

